registration/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from registration.views import (
    UserCreateView,
    UserUpdateView,
    UserDeleteView,
    user_confirm_deletion_view,
)

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register/", UserCreateView.as_view(), name="register"),
    path("<int:pk>/update/", UserUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", UserDeleteView.as_view(), name="delete"),
    path(
        "<int:pk>/confirm_deletion/",
        user_confirm_deletion_view,
        name="confirm-deletion",
    ),
    path(
        "settings/",
        TemplateView.as_view(template_name="registration/settings.html"),
        name="settings",
    ),
]

app_name = "registration"

todo/urls.py
from django.urls import path

from todo.views import (
    index_view,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TagDetailView,
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskDetailView,
    change_status_view,
    switch_pinned_view,
    about_view,
)

urlpatterns = [
    path("", index_view, name="index"),
    path("about/", about_view, name="about"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/<int:pk>/", TagDetailView.as_view(), name="tag-detail"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"
    ),
    path(
        "tasks/<int:pk>/change_status/",
        change_status_view,
        name="task-change-status",
    ),
    path(
        "tasks/<int:pk>/switch_pinned/",
        switch_pinned_view,
        name="task-switch-pinned",
    ),
]

app_name = "todo"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "registration/", include("registration.urls", namespace="registration")
    ),
    path("", include("todo.urls", namespace="todo")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?name={{ request.GET.name }}&page={{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?name={{ request.GET.name }}&page={{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
 {% load static %}


<img src="{% static 'images/schedule.png' %}" style="max-width: 100%;max-height: 100%;">

{% if user.is_authenticated %}
  <br>
  <ul class="sidebar-nav list-group sidebar">
    <li class="list-group-item sidebar-list-item"><strong>User:</strong> {{ user.username }}</li>
    <li class="list-group-item sidebar-list-item"><a href="{% url 'registration:logout' %}">Logout</a></li>
  </ul>
  <br>
  <ul class="sidebar-nav list-group">
    <li class="list-group-item sidebar-list-item"><a href="{% url 'todo:index' %}">Home</a></li>
    <li class="list-group-item sidebar-list-item"><a href="{% url 'todo:task-list' %}">Tasks</a></li>
    <li class="list-group-item sidebar-list-item"><a href="{% url 'todo:tag-list' %}">Tags</a></li>
    <li class="list-group-item sidebar-list-item"><a href="{% url 'registration:settings' %}">Settings</a></li>
    <li class="list-group-item sidebar-list-item"><a href="{% url 'todo:about' %}">About</a></li>
  </ul>
{% else %}
  <br>
  <ul class="sidebar-nav list-group sidebar">
    <li class="list-group-item sidebar-list-item"><a href="{% url 'registration:login' %}">Login</a></li>
    <li class="list-group-item sidebar-list-item"><a href="{% url 'registration:register' %}">Register</a></li>
    <li class="list-group-item sidebar-list-item"><a href="{% url 'todo:about' %}">About</a></li>
  </ul>
  <br>
{% endif %}