todo/urls.py
from django.urls import path

from todo.views import (
    index_view,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TagDetailView,
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskDetailView,
    change_status_view,
    switch_pinned_view,
    about_view,
)

urlpatterns = [
    path("", index_view, name="index"),
    path("about/", about_view, name="about"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/<int:pk>/", TagDetailView.as_view(), name="tag-detail"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"
    ),
    path(
        "tasks/<int:pk>/change_status/",
        change_status_view,
        name="task-change-status",
    ),
    path(
        "tasks/<int:pk>/switch_pinned/",
        switch_pinned_view,
        name="task-switch-pinned",
    ),
]

app_name = "todo"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "registration/", include("registration.urls", namespace="registration")
    ),
    path("", include("todo.urls", namespace="todo")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/models.py
from textwrap import shorten
from datetime import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models

from pytz import timezone

from todo_list import settings


class Tag(models.Model):
    user = models.ForeignKey(
        "registration.User",
        related_name="tags",
        on_delete=models.CASCADE,
    )
    name = models.CharField(max_length=63)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user_id", "name"], name="name_user_unique"
            ),
        ]

    def __str__(self) -> str:
        return self.name


class Task(models.Model):
    STATUS_CHOICES = (
        (True, "Done"),
        (False, "Not done"),
    )

    PRIORITY_CHOICES = (
        (1, "Highest"),
        (2, "Critical"),
        (3, "Alarming"),
        (4, "Act soon"),
        (5, "Low"),
    )
    user = models.ForeignKey(
        "registration.User", related_name="tasks", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=255)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField()
    status = models.BooleanField(default=False, choices=STATUS_CHOICES)
    priority = models.IntegerField(default=3, choices=PRIORITY_CHOICES)
    pinned = models.BooleanField(default=False)
    tags = models.ManyToManyField("Tag", related_name="tasks")

    @property
    def shorten_description(self) -> str:
        return shorten(self.description, width=50, placeholder="...")

    @property
    def status_display_name(self) -> str:
        for status_code, status_display_name in Task.STATUS_CHOICES:
            if status_code == self.status:
                return status_display_name

    @property
    def priority_display_name(self) -> str:
        for priority_code, priority_display_name in Task.PRIORITY_CHOICES:
            if priority_code == self.priority:
                return priority_display_name

    @property
    def deadline_expired(self) -> bool:
        return self.deadline < datetime.now(tz=timezone(settings.TIME_ZONE))

    def __str__(self) -> str:
        return f"{self.name}, created at {self.created_at} (deadline {self.deadline})"

todo/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.db.models import Q

from todo.models import Task, Tag


class TagForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        super().__init__(*args, **kwargs)

        if self.instance.id is not None:
            self.fields["name"].value = self.instance.name

    class Meta:
        model = Tag
        fields = ["name"]

    def clean_name(self):
        name = self.cleaned_data["name"]

        if Tag.objects.filter(Q(user_id=self.user.id) & Q(name=name)).exists():
            raise ValidationError(
                "This tag is already represented in your list!"
            )

        return name


class TaskForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user")
        super().__init__(*args, **kwargs)

        self.fields["tags"].queryset = Tag.objects.filter(user_id=user.id)

        self.fields["tags"].required = False
        self.fields["description"].required = False

        self.fields["priority"].choices = Task.PRIORITY_CHOICES

        if self.instance.id is not None:
            self.fields["name"].value = self.instance.name
            self.fields["deadline"].value = self.instance.deadline.strftime(
                "%Y-%m-%dT%H:%M"
            )
            self.fields["description"].value = self.instance.description
            self.fields["priority"].value = self.instance.priority
            self.fields["tags"].values = {
                tag.id: tag for tag in self.instance.tags.all()
            }

    class Meta:
        model = Task
        fields = ["name", "description", "deadline", "priority", "tags"]

todo/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.http import (
    HttpResponseRedirect,
    HttpRequest,
    HttpResponse,
    Http404,
)
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

from todo.forms import TaskForm, TagForm
from todo.functions import get_page_number_after_deletion
from todo.mixins import (
    TagVerifyUrlDataMixin,
    TaskVerifyUrlDataMixin,
    FormKwargsMixin,
    FormValidMixin,
)
from todo.models import Tag, Task


@login_required
def index_view(request: HttpRequest) -> HttpResponse:
    tasks_count = Task.objects.filter(user_id=request.user.id).count()
    finished_tasks_count = Task.objects.filter(Q(user_id=request.user.id) & Q(status=True)).count()

    request.session["num_visits"] = request.session.get("num_visits", 0) + 1

    context = {
        "tasks_count": tasks_count,
        "finished_tasks_count": finished_tasks_count,
        "num_visits": request.session["num_visits"],
        "test": "data",
    }

    return render(request, "todo/index.html", context=context)


def about_view(request: HttpRequest) -> HttpResponse:
    return render(request, "todo/about.html")


class TagListView(LoginRequiredMixin, generic.ListView):
    model = Tag
    paginate_by = 8

    def get_queryset(self):
        queryset = Tag.objects.filter(user_id=self.request.user.id).order_by(
            "-created_at"
        )

        name = self.request.GET.get("name")
        if name:
            return queryset.filter(name__icontains=name)

        return queryset


class TagDetailView(
    LoginRequiredMixin, TagVerifyUrlDataMixin, generic.DetailView
):
    model = Tag


class TagCreateView(
    LoginRequiredMixin, SuccessMessageMixin, FormKwargsMixin, FormValidMixin, generic.CreateView
):
    form_class = TagForm
    template_name = "todo/tag_form.html"
    success_message = "Tag was successfully created"

    def get_success_url(self):
        return f"{reverse('todo:tag-list')}?name={self.request.GET.get('name', '')}&page={self.request.GET.get('page', 1)}"


class TagUpdateView(
    LoginRequiredMixin,
    TagVerifyUrlDataMixin,
    SuccessMessageMixin,
    FormKwargsMixin,
    generic.UpdateView,
):
    model = Tag
    form_class = TagForm
    success_message = "Tag was successfully updated"

    def get_success_url(self):
        return f"{reverse('todo:tag-list')}?name={self.request.GET.get('name', '')}&page={self.request.GET.get('page', 1)}"


class TagDeleteView(
    LoginRequiredMixin, TagVerifyUrlDataMixin, generic.DeleteView
):
    model = Tag

    def get_success_url(self):
        page = int(self.request.GET.get("page", 1))
        count = int(self.request.GET.get("count", 1))
        per_page = int(self.request.GET.get("per_page", 1))

        new_page = get_page_number_after_deletion(page, count, per_page)

        messages.add_message(self.request, messages.SUCCESS, "Tag was successfully deleted")
        return f"{reverse('todo:tag-list')}?name={self.request.GET.get('name', '')}&page={new_page}"


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    paginate_by = 4

    def get_queryset(self):
        queryset = Task.objects.filter(user_id=self.request.user.id).order_by(
            "-pinned", "-priority", "deadline"
        )

        name = self.request.GET.get("name")
        if name:
            return queryset.filter(name__icontains=name)

        return queryset


class TaskDetailView(
    LoginRequiredMixin, TaskVerifyUrlDataMixin, generic.DetailView
):
    model = Task


class TaskCreateView(
    LoginRequiredMixin, SuccessMessageMixin, FormKwargsMixin, FormValidMixin, generic.CreateView
):
    form_class = TaskForm
    template_name = "todo/task_form.html"
    success_message = "Task was successfully created"

    def get_success_url(self):
        return f"{reverse('todo:task-list')}?name={self.request.GET.get('name', '')}&page={self.request.GET['page']}"


class TaskUpdateView(
    LoginRequiredMixin,
    TaskVerifyUrlDataMixin,
    SuccessMessageMixin,
    FormKwargsMixin,
    generic.UpdateView,
):
    model = Task
    form_class = TaskForm
    success_message = "Task was successfully updated"

    def get_success_url(self):
        return f"{reverse('todo:task-list')}?name={self.request.GET.get('name', '')}&page={self.request.GET['page']}"


class TaskDeleteView(
    LoginRequiredMixin, TaskVerifyUrlDataMixin, generic.DeleteView
):
    model = Task

    def get_success_url(self):
        page = int(self.request.GET.get("page", 1))
        count = int(self.request.GET.get("count", 1))
        per_page = int(self.request.GET.get("per_page", 1))

        new_page = get_page_number_after_deletion(page, count, per_page)

        messages.add_message(self.request, messages.SUCCESS, "Task was successfully deleted")
        return f"{reverse('todo:task-list')}?name={self.request.GET.get('name', '')}&page={new_page}"


def change_status_view(request, pk: int):
    task = get_object_or_404(Task, pk=pk)

    if task.user_id != request.user.id:
        raise Http404()

    task.status = not task.status
    task.save()

    return HttpResponseRedirect(
        f"{reverse('todo:task-list')}?name={request.GET.get('name', '')}&page={request.GET.get('page', 1)}"
    )


def switch_pinned_view(request, pk: int):
    task = get_object_or_404(Task, pk=pk)

    if task.user_id != request.user.id:
        raise Http404()

    task.pinned = not task.pinned
    task.save()

    return HttpResponseRedirect(
        f"{reverse('todo:task-list')}?name={request.GET.get('name', '')}&page={request.GET.get('page', 1)}"
    )

templates/todo/about.html
{% extends "base.html" %}
{% load static %}


{% block content %}
  <h1>About project</h1>

  <br>

  <p><strong>This project create to help people manage their tasks</strong></p>
  <p><strong><a href="https://github.com/pazyn404/todo-list-project">Project GitHub repository</a></strong></p>
  <br>

  <p>
    <strong>
      Check also my accounts:
      <a href="https://github.com/pazyn404"><img src="{% static 'images/github.png' %}"></a>
      <a href="https://www.linkedin.com/in/yurii-pazyn-4a99bb255/"><img src="{% static 'images/linkedin.png' %}"></a>
    </strong>
  </p>

{% endblock %}

templates/todo/index.html
{% extends "base.html" %}


{% block content %}

  <h1>Home page:</h1>

  {% if num_visits == 1 %}
    <h3>Hi, {{ user.first_name }}!</h3>
  {% else %}
    <h3>Welcome back, {{ user.first_name }}!</h3>
  {% endif %}

  <br>

  {% if tasks_count == 0 %}
    <h3>Create new task and finish it!</h3>
  {% else %}
    {% if finished_tasks_count > 1 %}
      <h3>You have already {{ finished_tasks_count }} finished tasks!</h3>
    {% elif finished_tasks_count == 1 %}
      <h3>You have already {{ finished_tasks_count }} finished task!</h3>
    {% else %}
      <h3>You have no finished task yet, fix it!</h3>
    {% endif %}
  {% endif %}


{% endblock %}

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}


{% block content %}
  <form method="post" action="">
    {% csrf_token %}
    <p><strong>This tag will be deleted from all of the tasks</strong></p>
    <p>
      <input type="submit" value="Confirm" class="btn btn-danger">
      <a onclick="window.history.back()" class="btn btn-secondary">Cancel</a>
    </p>
  </form>
{% endblock %}

templates/todo/tag_detail.html
{% extends "base.html" %}


{% block content %}

  <h3>{{ tag.name }}</h3>
  <p><strong>Created at:</strong> {{ tag.created_at }}</p>
  <p><strong>Tasks count usage:</strong> {{ tag.tasks.count }}</p>

{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}


{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>

  <form method="post" action="">
    {% csrf_token %}

    <div class="item-container">
      <label class="label">Name</label>
      <input type="text" name="name" value="{{ form.fields.name.value }}" class="text">
      <span class="validation-error">{{ form.errors.name }}</span>
    </div>

    <input type="submit" value="{{ object|yesno:"Update,Create" }}" class="btn btn-success">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}


{% block content %}
    <h1>
      Tag List
      <a href="{% url 'todo:tag-create' %}?name={{ request.GET.name }}&page={{ page_obj.number }}" class="btn btn-primary">Add tag</a>
    </h1>

    <form action="{% url 'todo:tag-list' %}" method="get" class="form-inline">
      <input type="text" name="name" value="{{ request.GET.name }}" placeholder="Search by name" class="text">
      <input type="submit" value="🔍" class="btn btn-primary btn-sm btn-search">
    </form>

    <br>

    {% if tag_list %}
      <ul class="list-group">
        {% for tag in tag_list %}
            <li class="list-group-item tag-list-item">
              <a href = "{% url 'todo:tag-detail' pk=tag.pk %}"><strong>{{ tag.name }}</strong></a>
              <a href="{% url 'todo:tag-update' pk=tag.pk %}?name={{ request.GET.name }}&page={{ page_obj.number }}" class="btn btn-sm btn-warning">Update</a>
              <a href="{% url 'todo:tag-delete' pk=tag.pk %}?name={{ request.GET.name }}&page={{ page_obj.number }}&count={{ page_obj.paginator.count }}&per_page={{ page_obj.paginator.per_page }}" class="btn btn-sm btn-danger">Delete</a>
            </li>
        {% endfor %}
      </ul>
    {% else %}
      <p><strong>No tags, add new one!</strong></p>
    {% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}


{% block content %}
  <form method="post" action="">
    {% csrf_token %}
    <p>
      <strong>Confirm task delete</strong>
    </p>
    <p>
      <input type="submit" value="Confirm" class="btn btn-danger">
      <a onclick="window.history.back()" class="btn btn-secondary">Cancel</a>
    </p>
  </form>
{% endblock %}

templates/todo/task_detail.html
{% extends "base.html" %}


{% block content %}
  <h3>{{ task.name }}</h3>

  <p><strong>Status:</strong> {{ task.status_display_name }}</p>
  <p><strong>Priority:</strong> {{ task.priority_display_name }}</p>
  <p><strong>Created at:</strong> {{ task.created_at }}</p>
  <p><strong>Deadline:</strong> {{ task.deadline }}</p>

  <p>
    <strong>Description:</strong>
    {% if task.description %}
      {{ task.description }}
    {% else %}
      <span>description is not provided</span>
    {% endif %}
  </p>

  <p>
    <strong>Tags:</strong>
    {% if task.tags.all %}
      {% for tag in task.tags.all %}
        <span>{{ tag }}</span>
      {% endfor %}
    {% else %}
        <span>tags is not provided</span>
    {% endif %}
  </p>

{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}


{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>

  <form method="post" action="">
    {% csrf_token %}

    <div class="item-container">
      <label class="label">Name</label>
      <input type="text" name="name" value="{{ form.fields.name.value }}" class="text" required>
    </div>

    <div class="item-container">
      <label class="label">Deadline</label>
      <input type="datetime-local" name="deadline" value="{{ form.fields.deadline.value }}" class="datetime" required>
      <span class="validation-error">{{ form.errors.deadline }}</span>
    </div>

    <div class="item-container">
      <label class="label">Description</label>
      <textarea name="description" placeholder="Description is not provided" class="textarea">{{ form.fields.description.value }}</textarea>
    </div>

    <div class="item-container">
      <label class="label">Priority</label>

      <select name="priority" class="select" required>
        {% for priority in form.fields.priority.choices %}
          {% if priority.0 == form.fields.priority.value %}
            <option value="{{ priority.0 }}" selected>{{ priority.1 }}</option>
          {% else %}
            <option value="{{ priority.0 }}">{{ priority.1 }}</option>
          {% endif %}
        {% endfor %}
      </select>

    </div>
    {% if form.fields.tags.queryset.all %}
      <div class="item-container">
        <label class="label">Tags</label>

        <select name="tags" class="select" multiple>
          {% for tag in form.fields.tags.queryset.all %}
            {% if tag.id in form.fields.tags.values %}
              <option value="{{ tag.id }}" selected>{{ tag }}</option>
            {% else %}
              <option value="{{ tag.id }}">{{ tag }}</option>
            {% endif %}
          {% endfor %}
        </select>

      </div>
    {% endif %}

    <input type="submit" value="{{ object|yesno:"Update,Create" }}" class="btn btn-success">
  </form>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}


{% block content %}
  <h1>
    TODO List
    <a href="{% url 'todo:task-create' %}?name={{ request.GET.name }}&page={{ page_obj.number }}" class="btn btn-primary">Add task</a>
  </h1>
  <br>
  <form action="{% url 'todo:task-list' %}" method="get" class="form-inline">
    <input type="text" name="name" value="{{ request.GET.name }}" placeholder="Search by name" class="text">
    <input type="submit" value="🔍" class="btn btn-primary btn-sm btn-search">
  </form>
  <br>

  {% if task_list %}

    <ul class="list-group">
      {% for task in task_list %}
          <li class="list-group-item task-list-item">

            <p>
              <a href="{% url 'todo:task-detail' pk=task.pk %}"><strong>{{ task.name }}</strong></a>

              {% if task.status %}
                <a href="{% url 'todo:task-change-status' pk=task.pk %}?name={{ request.GET.name }}&page={{ page_obj.number }}" class="btn btn-sm btn-success">{{ task.status_display_name }}</a>
              {% else %}
                <a href="{% url 'todo:task-change-status' pk=task.pk %}?name={{ request.GET.name }}&page={{ page_obj.number }}" class="btn btn-sm btn-secondary">{{ task.status_display_name }}</a>
              {% endif %}

              {% if task.pinned %}
                <a href="{% url 'todo:task-switch-pinned' pk=task.pk %}?name={{ request.GET.name }}&page={{ page_obj.number }}" class="btn btn-sm btn-secondary">Unpin</a>
              {% else %}
                <a href="{% url 'todo:task-switch-pinned' pk=task.pk %}?name={{ request.GET.name }}&page={{ page_obj.number }}" class="btn btn-sm btn-secondary">Pin</a>
              {% endif %}
              <a href="{% url 'todo:task-update' pk=task.pk %}?name={{ request.GET.name }}&page={{ page_obj.number }}" class="btn btn-sm btn-warning">Update</a>
              <a href="{% url 'todo:task-delete' pk=task.pk %}?name={{ request.GET.name }}&page={{ page_obj.number }}&count={{ page_obj.paginator.count }}&per_page={{ page_obj.paginator.per_page }}" class="btn btn-sm btn-danger">Delete</a>
            </p>

            <p>
              <strong>Priority:</strong> {{ task.priority_display_name }}

              {% if not task.status and task.deadline_expired %}
                <strong class="expired_deadline">Expired deadline: </strong>{{ task.deadline }}
              {% endif %}
            </p>

            <p>
              <strong>Description:</strong> {{ task.shorten_description }}
            </p>

          </li>
      {% endfor %}
    </ul>

  {% else %}
    <p><strong>No tasks, add new one!</strong></p>
  {% endif %}

{% endblock %}